name: Deploy new release to production
on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Set up SSH Key
            env:
              SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
              SSH_HOST: ${{ secrets.ARTIFACT_HOST }}
            run: |
              mkdir -p ~/.ssh
              echo "$SSH_KEY" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              ssh-keyscan -H -p 22 "$SSH_HOST" >> ~/.ssh/known_hosts

          - name: Deploy new code
            env:
              SSH_USER: ${{ secrets.USER }}
              SSH_HOST: ${{ secrets.ARTIFACT_HOST }}
              APP_PATH: ${{ secrets.APP_PATH }}
              RELEASE_TAG: ${{ github.event.release.tag_name }}
            run: |
              ssh -i ~/.ssh/id_ed25519 "$SSH_USER@$SSH_HOST" <<'ENDSSH'
              set -euo pipefail
              cd "${APP_PATH}/prod/kod-proteinfold"
              git fetch --all
              git reset --hard "$RELEASE_TAG"
              ENDSSH
